name: businessmodelcanvas
channels:
  - blaze
  - defaults
  - conda-forge
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - altair=5.5.0
  - aom=3.6.0
  - arrow-cpp=21.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - cffi=2.0.0
  - colorama=0.4.6
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.15.0
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.43
  - glog=0.5.0
  - google-api-python-client=2.185.0
  - google-auth-httplib2=0.2.0
  - google-generativeai=0.8.5
  - graphite2=1.3.14
  - greenlet=3.2.4
  - h11=0.16.0
  - harfbuzz=10.2.0
  - httpcore=1.0.9
  - httplib2=0.31.0
  - httpx=0.28.1
  - icu=73.1
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.15.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.16
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - narwhals=2.7.0
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - ollama-python=0.6.0
  - openjpeg=2.5.2
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - proto-plus=1.26.1
  - pyarrow=21.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycares=4.10.0
  - pycparser=2.23
  - pydantic=2.12.2
  - pydantic-core=2.41.4
  - pyopenssl=25.0.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pytesseract=0.3.13
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - sqlalchemy=2.0.43
  - sqlite=3.50.2
  - sqlite3=3.8.6
  - streamlit=1.50.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tenacity=9.1.2
  - tk=8.6.15
  - toml=0.10.2
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uritemplate=4.2.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winloop=0.2.2
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiosqlite==0.21.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - blockbuster==1.5.25
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - comm==0.2.3
      - cryptography==44.0.3
      - dataclasses-json==0.6.7
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - dydantic==0.0.8
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filetype==1.2.0
      - forbiddenfruit==0.1.4
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - google-ai-generativelanguage==0.7.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - grpcio-status==1.75.1
      - httpx-sse==0.4.1
      - idna==3.10
      - ipykernel==6.30.1
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jiter==0.11.0
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-rs==0.29.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - langchain==0.3.27
      - langchain-community==0.3.29
      - langchain-core==0.3.76
      - langchain-google-genai==2.1.12
      - langchain-openai==0.3.33
      - langchain-tavily==0.2.11
      - langchain-text-splitters==0.3.11
      - langgraph==0.6.7
      - langgraph-api==0.4.27
      - langgraph-checkpoint==2.1.1
      - langgraph-checkpoint-sqlite==2.0.11
      - langgraph-cli==0.4.2
      - langgraph-prebuilt==0.6.4
      - langgraph-runtime-inmem==0.14.0
      - langgraph-sdk==0.2.9
      - langsmith==0.4.31
      - lark==1.3.0
      - marshmallow==3.26.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - openai==1.109.1
      - orjson==3.11.3
      - ormsgpack==1.10.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - platformdirs==4.4.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - pure-eval==0.2.3
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pymupdf==1.26.5
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - pywin32==311
      - pywinpty==3.0.0
      - pyzmq==27.1.0
      - referencing==0.36.2
      - regex==2025.9.18
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlite-vec==0.1.6
      - sse-starlette==2.1.3
      - stack-data==0.6.3
      - starlette==0.48.0
      - structlog==25.4.0
      - tavily-python==0.7.12
      - terminado==0.18.1
      - tiktoken==0.11.0
      - tinycss2==1.4.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - trustcall==0.0.39
      - truststore==0.10.4
      - types-python-dateutil==2.9.0.20250822
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - uvicorn==0.37.0
      - watchfiles==1.1.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wikipedia==1.4.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.25.0
